### ISSUE TITLE
Example typo

### ISSUE THREAD

**Issue by moeiscool** [rearley/ebay#4]
example is

$trading = new \Ebay\Service\Finding();
$finding = new \Ebay\Service\Shopping();
$shopping = new \Ebay\Service\Trading();

should probably be

$finding = new \Ebay\Service\Finding();
$shopping = new \Ebay\Service\Shopping();
$trading = new \Ebay\Service\Trading();

**Comment by rearley** [comment]
Thanks for pointing this out. I have fixed the documentation.
